// approx_mul.sv -- 8x8 unsigned Dadda multiplier with truncation depth N.
//
// How it works:
//   1. Partial products. Multiplying a by b creates 64 one-bit terms
//      pp(i, j) = a[j] & b[i], each worth 2^(i+j). Terms with the same i+j
//      form "column" i+j.
//   2. Truncation (the approximation). Every term in the lowest N columns
//      (i + j < N) is replaced by a constant 0. N = 0 keeps everything, so the
//      multiplier is exact; larger N drops more terms, saving hardware but
//      making the product slightly too small (never too large).
//   3. Reduction. The Dadda tree (dadda8_reduce, generated by
//      scripts/gen_dadda.py) adds the columns down to two 16-bit rows.
//   4. Final addition. The two rows are added with a behavioral "+"; Yosys
//      chooses the adder circuit for this last step.
//
// Note: the tree itself is the same for every N. We do not re-plan it; the
// synthesis tool deletes the adders whose inputs are all constant 0
// ("constant propagation"), which is where the hardware saving comes from.

module approx_mul #(
    parameter int N = 0            // truncation depth: number of dropped columns, 0..12
) (
    input  logic [7:0]  a,         // first operand, unsigned
    input  logic [7:0]  b,         // second operand, unsigned
    output logic [15:0] p          // approximate product (exact when N = 0)
);
    // All 64 partial products in one packed vector: pp[i*8 + j] = a[j] & b[i].
    logic [63:0] pp;

    // A generate loop builds one AND gate (or one constant 0) per term.
    genvar i, j;
    generate
        for (i = 0; i < 8; i++) begin : g_row          // i = bit of b
            for (j = 0; j < 8; j++) begin : g_col      // j = bit of a
                if (i + j >= N) begin : g_keep
                    assign pp[i*8 + j] = a[j] & b[i];  // kept term
                end else begin : g_drop
                    assign pp[i*8 + j] = 1'b0;         // dropped (truncated) term
                end
            end
        end
    endgenerate

    // Dadda reduction tree: 64 bits -> two 16-bit rows.
    logic [15:0] row0, row1;
    dadda8_reduce u_tree (
        .pp   (pp),
        .row0 (row0),
        .row1 (row1)
    );

    // Final carry-propagate adder (behavioral "+", as allowed by the spec).
    assign p = row0 + row1;
endmodule
