// dadda8_reduce.sv -- GENERATED by scripts/gen_dadda.py. Do not edit by hand;
// change the script and re-run:  python scripts/gen_dadda.py
//
// Reduction tree of an 8x8 Dadda multiplier.
//   Input : pp[i*8+j] = a[j] & b[i], the 64 partial-product bits.
//           pp[i*8+j] belongs to column i+j and is worth 2^(i+j).
//   Output: two 16-bit rows. row0 + row1 = sum of all partial products.
//
// Each stage uses full adders (FA: 3 bits -> sum here + carry to the next
// column) and half adders (HA: 2 bits -> sum here + carry) to bring every
// column down to the stage's target height (Dadda sequence 6, 4, 3, 2).
//
// Column heights before each stage (column 0 on the left):
//   stage 1 (target 6): 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 0   -> 3 FA, 3 HA
//   stage 2 (target 4): 1 2 3 4 5 6 6 6 6 6 6 4 3 2 1 0   -> 12 FA, 2 HA
//   stage 3 (target 3): 1 2 3 4 4 4 4 4 4 4 4 4 4 2 1 0   -> 9 FA, 1 HA
//   stage 4 (target 2): 1 2 3 3 3 3 3 3 3 3 3 3 3 3 1 0   -> 11 FA, 1 HA
//   final: 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0
// Total: 35 full adders, 7 half adders.
//
// Truncation is done OUTSIDE this module (approx_mul.sv ties dropped
// partial products to 0); synthesis removes adders fed only by zeros.

module dadda8_reduce (
    input  logic [63:0] pp,     // partial products, pp[i*8+j] = a[j] & b[i]
    output logic [15:0] row0,   // first final row
    output logic [15:0] row1    // second final row (row0 + row1 = product)
);

    // ---- Stage 1: reduce every column to at most 6 bits ----
    logic s1_c6_ha0_sum, s1_c6_ha0_cout;
    half_adder u_s1_c6_ha0 (.a(pp[6]), .b(pp[13]), .sum(s1_c6_ha0_sum), .cout(s1_c6_ha0_cout));  // column 6
    logic s1_c7_fa0_sum, s1_c7_fa0_cout;
    full_adder u_s1_c7_fa0 (.a(pp[7]), .b(pp[14]), .cin(pp[21]), .sum(s1_c7_fa0_sum), .cout(s1_c7_fa0_cout));  // column 7
    logic s1_c7_ha0_sum, s1_c7_ha0_cout;
    half_adder u_s1_c7_ha0 (.a(pp[28]), .b(pp[35]), .sum(s1_c7_ha0_sum), .cout(s1_c7_ha0_cout));  // column 7
    logic s1_c8_fa0_sum, s1_c8_fa0_cout;
    full_adder u_s1_c8_fa0 (.a(pp[15]), .b(pp[22]), .cin(pp[29]), .sum(s1_c8_fa0_sum), .cout(s1_c8_fa0_cout));  // column 8
    logic s1_c8_ha0_sum, s1_c8_ha0_cout;
    half_adder u_s1_c8_ha0 (.a(pp[36]), .b(pp[43]), .sum(s1_c8_ha0_sum), .cout(s1_c8_ha0_cout));  // column 8
    logic s1_c9_fa0_sum, s1_c9_fa0_cout;
    full_adder u_s1_c9_fa0 (.a(pp[23]), .b(pp[30]), .cin(pp[37]), .sum(s1_c9_fa0_sum), .cout(s1_c9_fa0_cout));  // column 9

    // ---- Stage 2: reduce every column to at most 4 bits ----
    logic s2_c4_ha0_sum, s2_c4_ha0_cout;
    half_adder u_s2_c4_ha0 (.a(pp[4]), .b(pp[11]), .sum(s2_c4_ha0_sum), .cout(s2_c4_ha0_cout));  // column 4
    logic s2_c5_fa0_sum, s2_c5_fa0_cout;
    full_adder u_s2_c5_fa0 (.a(pp[5]), .b(pp[12]), .cin(pp[19]), .sum(s2_c5_fa0_sum), .cout(s2_c5_fa0_cout));  // column 5
    logic s2_c5_ha0_sum, s2_c5_ha0_cout;
    half_adder u_s2_c5_ha0 (.a(pp[26]), .b(pp[33]), .sum(s2_c5_ha0_sum), .cout(s2_c5_ha0_cout));  // column 5
    logic s2_c6_fa0_sum, s2_c6_fa0_cout;
    full_adder u_s2_c6_fa0 (.a(s1_c6_ha0_sum), .b(pp[20]), .cin(pp[27]), .sum(s2_c6_fa0_sum), .cout(s2_c6_fa0_cout));  // column 6
    logic s2_c6_fa1_sum, s2_c6_fa1_cout;
    full_adder u_s2_c6_fa1 (.a(pp[34]), .b(pp[41]), .cin(pp[48]), .sum(s2_c6_fa1_sum), .cout(s2_c6_fa1_cout));  // column 6
    logic s2_c7_fa0_sum, s2_c7_fa0_cout;
    full_adder u_s2_c7_fa0 (.a(s1_c6_ha0_cout), .b(s1_c7_fa0_sum), .cin(s1_c7_ha0_sum), .sum(s2_c7_fa0_sum), .cout(s2_c7_fa0_cout));  // column 7
    logic s2_c7_fa1_sum, s2_c7_fa1_cout;
    full_adder u_s2_c7_fa1 (.a(pp[42]), .b(pp[49]), .cin(pp[56]), .sum(s2_c7_fa1_sum), .cout(s2_c7_fa1_cout));  // column 7
    logic s2_c8_fa0_sum, s2_c8_fa0_cout;
    full_adder u_s2_c8_fa0 (.a(s1_c7_fa0_cout), .b(s1_c7_ha0_cout), .cin(s1_c8_fa0_sum), .sum(s2_c8_fa0_sum), .cout(s2_c8_fa0_cout));  // column 8
    logic s2_c8_fa1_sum, s2_c8_fa1_cout;
    full_adder u_s2_c8_fa1 (.a(s1_c8_ha0_sum), .b(pp[50]), .cin(pp[57]), .sum(s2_c8_fa1_sum), .cout(s2_c8_fa1_cout));  // column 8
    logic s2_c9_fa0_sum, s2_c9_fa0_cout;
    full_adder u_s2_c9_fa0 (.a(s1_c8_fa0_cout), .b(s1_c8_ha0_cout), .cin(s1_c9_fa0_sum), .sum(s2_c9_fa0_sum), .cout(s2_c9_fa0_cout));  // column 9
    logic s2_c9_fa1_sum, s2_c9_fa1_cout;
    full_adder u_s2_c9_fa1 (.a(pp[44]), .b(pp[51]), .cin(pp[58]), .sum(s2_c9_fa1_sum), .cout(s2_c9_fa1_cout));  // column 9
    logic s2_c10_fa0_sum, s2_c10_fa0_cout;
    full_adder u_s2_c10_fa0 (.a(s1_c9_fa0_cout), .b(pp[31]), .cin(pp[38]), .sum(s2_c10_fa0_sum), .cout(s2_c10_fa0_cout));  // column 10
    logic s2_c10_fa1_sum, s2_c10_fa1_cout;
    full_adder u_s2_c10_fa1 (.a(pp[45]), .b(pp[52]), .cin(pp[59]), .sum(s2_c10_fa1_sum), .cout(s2_c10_fa1_cout));  // column 10
    logic s2_c11_fa0_sum, s2_c11_fa0_cout;
    full_adder u_s2_c11_fa0 (.a(pp[39]), .b(pp[46]), .cin(pp[53]), .sum(s2_c11_fa0_sum), .cout(s2_c11_fa0_cout));  // column 11

    // ---- Stage 3: reduce every column to at most 3 bits ----
    logic s3_c3_ha0_sum, s3_c3_ha0_cout;
    half_adder u_s3_c3_ha0 (.a(pp[3]), .b(pp[10]), .sum(s3_c3_ha0_sum), .cout(s3_c3_ha0_cout));  // column 3
    logic s3_c4_fa0_sum, s3_c4_fa0_cout;
    full_adder u_s3_c4_fa0 (.a(s2_c4_ha0_sum), .b(pp[18]), .cin(pp[25]), .sum(s3_c4_fa0_sum), .cout(s3_c4_fa0_cout));  // column 4
    logic s3_c5_fa0_sum, s3_c5_fa0_cout;
    full_adder u_s3_c5_fa0 (.a(s2_c4_ha0_cout), .b(s2_c5_fa0_sum), .cin(s2_c5_ha0_sum), .sum(s3_c5_fa0_sum), .cout(s3_c5_fa0_cout));  // column 5
    logic s3_c6_fa0_sum, s3_c6_fa0_cout;
    full_adder u_s3_c6_fa0 (.a(s2_c5_fa0_cout), .b(s2_c5_ha0_cout), .cin(s2_c6_fa0_sum), .sum(s3_c6_fa0_sum), .cout(s3_c6_fa0_cout));  // column 6
    logic s3_c7_fa0_sum, s3_c7_fa0_cout;
    full_adder u_s3_c7_fa0 (.a(s2_c6_fa0_cout), .b(s2_c6_fa1_cout), .cin(s2_c7_fa0_sum), .sum(s3_c7_fa0_sum), .cout(s3_c7_fa0_cout));  // column 7
    logic s3_c8_fa0_sum, s3_c8_fa0_cout;
    full_adder u_s3_c8_fa0 (.a(s2_c7_fa0_cout), .b(s2_c7_fa1_cout), .cin(s2_c8_fa0_sum), .sum(s3_c8_fa0_sum), .cout(s3_c8_fa0_cout));  // column 8
    logic s3_c9_fa0_sum, s3_c9_fa0_cout;
    full_adder u_s3_c9_fa0 (.a(s2_c8_fa0_cout), .b(s2_c8_fa1_cout), .cin(s2_c9_fa0_sum), .sum(s3_c9_fa0_sum), .cout(s3_c9_fa0_cout));  // column 9
    logic s3_c10_fa0_sum, s3_c10_fa0_cout;
    full_adder u_s3_c10_fa0 (.a(s2_c9_fa0_cout), .b(s2_c9_fa1_cout), .cin(s2_c10_fa0_sum), .sum(s3_c10_fa0_sum), .cout(s3_c10_fa0_cout));  // column 10
    logic s3_c11_fa0_sum, s3_c11_fa0_cout;
    full_adder u_s3_c11_fa0 (.a(s2_c10_fa0_cout), .b(s2_c10_fa1_cout), .cin(s2_c11_fa0_sum), .sum(s3_c11_fa0_sum), .cout(s3_c11_fa0_cout));  // column 11
    logic s3_c12_fa0_sum, s3_c12_fa0_cout;
    full_adder u_s3_c12_fa0 (.a(s2_c11_fa0_cout), .b(pp[47]), .cin(pp[54]), .sum(s3_c12_fa0_sum), .cout(s3_c12_fa0_cout));  // column 12

    // ---- Stage 4: reduce every column to at most 2 bits ----
    logic s4_c2_ha0_sum, s4_c2_ha0_cout;
    half_adder u_s4_c2_ha0 (.a(pp[2]), .b(pp[9]), .sum(s4_c2_ha0_sum), .cout(s4_c2_ha0_cout));  // column 2
    logic s4_c3_fa0_sum, s4_c3_fa0_cout;
    full_adder u_s4_c3_fa0 (.a(s3_c3_ha0_sum), .b(pp[17]), .cin(pp[24]), .sum(s4_c3_fa0_sum), .cout(s4_c3_fa0_cout));  // column 3
    logic s4_c4_fa0_sum, s4_c4_fa0_cout;
    full_adder u_s4_c4_fa0 (.a(s3_c3_ha0_cout), .b(s3_c4_fa0_sum), .cin(pp[32]), .sum(s4_c4_fa0_sum), .cout(s4_c4_fa0_cout));  // column 4
    logic s4_c5_fa0_sum, s4_c5_fa0_cout;
    full_adder u_s4_c5_fa0 (.a(s3_c4_fa0_cout), .b(s3_c5_fa0_sum), .cin(pp[40]), .sum(s4_c5_fa0_sum), .cout(s4_c5_fa0_cout));  // column 5
    logic s4_c6_fa0_sum, s4_c6_fa0_cout;
    full_adder u_s4_c6_fa0 (.a(s3_c5_fa0_cout), .b(s3_c6_fa0_sum), .cin(s2_c6_fa1_sum), .sum(s4_c6_fa0_sum), .cout(s4_c6_fa0_cout));  // column 6
    logic s4_c7_fa0_sum, s4_c7_fa0_cout;
    full_adder u_s4_c7_fa0 (.a(s3_c6_fa0_cout), .b(s3_c7_fa0_sum), .cin(s2_c7_fa1_sum), .sum(s4_c7_fa0_sum), .cout(s4_c7_fa0_cout));  // column 7
    logic s4_c8_fa0_sum, s4_c8_fa0_cout;
    full_adder u_s4_c8_fa0 (.a(s3_c7_fa0_cout), .b(s3_c8_fa0_sum), .cin(s2_c8_fa1_sum), .sum(s4_c8_fa0_sum), .cout(s4_c8_fa0_cout));  // column 8
    logic s4_c9_fa0_sum, s4_c9_fa0_cout;
    full_adder u_s4_c9_fa0 (.a(s3_c8_fa0_cout), .b(s3_c9_fa0_sum), .cin(s2_c9_fa1_sum), .sum(s4_c9_fa0_sum), .cout(s4_c9_fa0_cout));  // column 9
    logic s4_c10_fa0_sum, s4_c10_fa0_cout;
    full_adder u_s4_c10_fa0 (.a(s3_c9_fa0_cout), .b(s3_c10_fa0_sum), .cin(s2_c10_fa1_sum), .sum(s4_c10_fa0_sum), .cout(s4_c10_fa0_cout));  // column 10
    logic s4_c11_fa0_sum, s4_c11_fa0_cout;
    full_adder u_s4_c11_fa0 (.a(s3_c10_fa0_cout), .b(s3_c11_fa0_sum), .cin(pp[60]), .sum(s4_c11_fa0_sum), .cout(s4_c11_fa0_cout));  // column 11
    logic s4_c12_fa0_sum, s4_c12_fa0_cout;
    full_adder u_s4_c12_fa0 (.a(s3_c11_fa0_cout), .b(s3_c12_fa0_sum), .cin(pp[61]), .sum(s4_c12_fa0_sum), .cout(s4_c12_fa0_cout));  // column 12
    logic s4_c13_fa0_sum, s4_c13_fa0_cout;
    full_adder u_s4_c13_fa0 (.a(s3_c12_fa0_cout), .b(pp[55]), .cin(pp[62]), .sum(s4_c13_fa0_sum), .cout(s4_c13_fa0_cout));  // column 13

    // ---- Final two rows: column c has at most two bits left ----
    assign row0[0] = pp[0];
    assign row1[0] = 1'b0;
    assign row0[1] = pp[1];
    assign row1[1] = pp[8];
    assign row0[2] = s4_c2_ha0_sum;
    assign row1[2] = pp[16];
    assign row0[3] = s4_c2_ha0_cout;
    assign row1[3] = s4_c3_fa0_sum;
    assign row0[4] = s4_c3_fa0_cout;
    assign row1[4] = s4_c4_fa0_sum;
    assign row0[5] = s4_c4_fa0_cout;
    assign row1[5] = s4_c5_fa0_sum;
    assign row0[6] = s4_c5_fa0_cout;
    assign row1[6] = s4_c6_fa0_sum;
    assign row0[7] = s4_c6_fa0_cout;
    assign row1[7] = s4_c7_fa0_sum;
    assign row0[8] = s4_c7_fa0_cout;
    assign row1[8] = s4_c8_fa0_sum;
    assign row0[9] = s4_c8_fa0_cout;
    assign row1[9] = s4_c9_fa0_sum;
    assign row0[10] = s4_c9_fa0_cout;
    assign row1[10] = s4_c10_fa0_sum;
    assign row0[11] = s4_c10_fa0_cout;
    assign row1[11] = s4_c11_fa0_sum;
    assign row0[12] = s4_c11_fa0_cout;
    assign row1[12] = s4_c12_fa0_sum;
    assign row0[13] = s4_c12_fa0_cout;
    assign row1[13] = s4_c13_fa0_sum;
    assign row0[14] = s4_c13_fa0_cout;
    assign row1[14] = pp[63];
    assign row0[15] = 1'b0;
    assign row1[15] = 1'b0;
endmodule
