"""Write results/flow_report.md: one readable report of the Yosys + OpenSTA flow.

Run after `make synth power sweep` (normally via `make report`). It only reads
files that the flow already wrote, so it takes a second:
  results/ppa_n0.csv, results/ppa_mul.csv   area and timing (flow/ppa.py)
  results/power_n0.csv                      power (flow/power.py)
  results/synth/*_stat.txt                  Yosys cell lists
  results/tool_versions.txt                 tool versions

Every number and every summary sentence is computed from those files, so the
report never needs hand editing. Relative changes are against approx_mul_N0.

Usage:  python flow/report.py [--out results/flow_report.md]
"""

import argparse
import re
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
from md_tables import (BASE, DESIGNS, RESULTS, load, md, pct,   # noqa: E402
                       table_cells, table_sta, table_sweep, table_timing_vs_n, table_yosys)


def tool_version(name):
    """One line from results/tool_versions.txt, e.g. 'yosys' -> 'Yosys 0.33 (...)'."""
    text = (RESULTS / "tool_versions.txt").read_text()
    m = re.search(rf"^{re.escape(name)}:\s*(.+)$", text, re.M)
    if not m:
        return "unknown (run `make versions`)"
    return m.group(1).replace("()", "").strip()


def table_power(p):
    """Power of N = 0 vs a*b, split into the parts OpenSTA reports."""
    rows = [
        ("multiplier logic (combinational)", "power_comb_uW"),
        ("flip-flops (sequential)", "power_seq_uW"),
        ("total", "power_total_uW"),
        ("of which: internal (inside the cells)", "internal_uW"),
        ("of which: switching (charging the nets)", "switching_uW"),
        ("of which: leakage", "leakage_uW"),
    ]
    t = pd.DataFrame([{"power (uW)": name, **{DESIGNS[d]: p.loc[d, col] for d in DESIGNS},
                       "a*b vs N=0": pct(p.loc["mul_behav", col], p.loc[BASE, col])}
                      for name, col in rows])
    return md(t)


def summary(a, p, s):
    """Key findings as bullet points, each computed from the CSVs."""
    base = s[s["design"] == BASE].iloc[0]
    approx = s[s["module"] == "approx_mul"]
    last = approx.iloc[-1]
    b, n0 = a.loc["mul_behav"], a.loc[BASE]
    pb, pn0 = p.loc["mul_behav"], p.loc[BASE]

    violations = int((s["setup_violations"] + s["hold_violations"]).sum())
    check = int(s["yosys_check_problems"].sum())
    sdc = int(s["sta_check_issues"].sum())
    other_warn = int((s["yosys_warnings"] - s["yosys_liberty_warnings"]).sum())
    area_falls = bool((approx["area_mul_um2"].diff().dropna() < 0).all())
    slower = [f"N = {r.N} ({pct(r.min_period_ns, base['min_period_ns'])})"
              for r in approx.itertuples() if r.min_period_ns > base["min_period_ns"]]

    lines = [
        f"- **{len(s)} designs** went through the flow: our multiplier for "
        f"N = {approx['N'].min()}..{approx['N'].max()} and the plain `a*b` reference.",
        f"- **Area:** {'falls at every step of N' if area_falls else 'does NOT fall at every step of N'}"
        f", from {base['area_mul_um2']} um^2 at N = 0 to {last['area_mul_um2']} um^2 at "
        f"N = {last['N']} ({pct(last['area_mul_um2'], base['area_mul_um2'])}).",
        f"- **Speed:** minimum clock period goes from {base['min_period_ns']} ns "
        f"({base['fmax_mhz']} MHz) at N = 0 to {last['min_period_ns']} ns ({last['fmax_mhz']} MHz) "
        f"at N = {last['N']} ({pct(last['min_period_ns'], base['min_period_ns'])}).",
    ]
    if slower:
        lines.append(
            f"- **Delay is not monotonic in N:** {', '.join(slower)} are slower than N = 0 although "
            "they contain less logic. ABC maps the logic without a timing target, so a small "
            "change in the logic can give a different critical path.")
    lines += [
        f"- **Exact design vs `a*b`:** `a*b` needs {pct(b['area_mul_um2'], n0['area_mul_um2'])} "
        f"area and {pct(pb['power_comb_uW'], pn0['power_comb_uW'])} multiplier power, and its "
        f"minimum clock period is {pct(b['min_period_ns'], n0['min_period_ns'])} "
        "(negative = faster).",
        f"- **Timing at the {p.loc[BASE, 'clk_ns']} ns clock:** {violations} setup/hold "
        f"violations in total, over all {len(s)} designs.",
        f"- **Checks:** {check} Yosys `check` problems and {sdc} OpenSTA `check_setup` problems "
        f"in total; {other_warn} Yosys warnings that are not about the liberty file.",
    ]
    return "\n".join(lines)


def report():
    a, p, s = load()
    stim = p.loc[BASE]
    sections = [
        "# Yosys + OpenSTA flow report",
        "Generated by `flow/report.py` from the files in `results/` "
        "(`make report`). Do not edit by hand.",

        "## Setup",
        "\n".join([
            f"- **Synthesis:** {tool_version('yosys')}: `synth -flatten`, `dfflibmap`, "
            "`abc -liberty` (`flow/synth.tcl`).",
            f"- **Timing and power:** OpenSTA {tool_version('opensta')} "
            f"(built from source, commit {tool_version('opensta src')[:8]}).",
            f"- **Gate-level simulation for power:** {tool_version('iverilog')}.",
            f"- **Cell library:** `{Path(tool_version('liberty')).name}`, SkyWater 130 nm "
            "`sky130_fd_sc_hd`, corner tt (typical), 25 C, 1.80 V.",
            f"- **Constraints:** `flow/mul_wrap.sdc`: {stim['clk_ns']} ns clock on `clk`, input "
            "and output delay 0, ideal clock (no clock tree).",
            "- **Wrapper:** each multiplier sits in `rtl/mul_wrap.sv` between input flip-flops "
            "(8 + 8) and output flip-flops (16). Multiplier area = total cell area minus those "
            "flip-flops.",
            f"- **Power stimulus:** {stim['cycles']:,} clock cycles of {stim['stimulus'].replace('_', ' ')} "
            f"inputs; activity on all {stim['annotated_pins']} pins comes from the simulation "
            "(none estimated).",
            "- **Pre-layout:** no wire parasitics. Compare designs with each other "
            "(relative to N = 0), not with numbers from other tools or processes.",
        ]),

        "## Summary",
        summary(a, p, s),

        "## 1. Area and delay for every N",
        table_sweep(s)[1],

        "## 2. Yosys: exact design (N = 0) vs a*b",
        table_yosys(a)[1],
        "Cells grouped by what they do:",
        table_cells()[1],
        "All Yosys warnings counted as \"liberty\" come from reading the cell library "
        "(scan and enable flip-flops whose pin functions Yosys cannot parse); the designs "
        "never use those cells.",

        "## 3. OpenSTA: exact design (N = 0) vs a*b",
        table_sta(a)[1],
        "- Min clock period = critical path + setup time of the capturing flip-flop.\n"
        "- Net delay is 0 because there are no wires before layout.\n"
        "- \"Hold slack, any path\" is an input pin going straight into an input flip-flop; it "
        "follows from the input delay of 0 in the SDC, not from the multiplier.",

        "## 4. Timing for every N",
        table_timing_vs_n(s)[1],

        "## 5. Power: exact design (N = 0) vs a*b",
        table_power(p),
        "Power for every N is not measured yet (Milestone 2, with image stimulus).",

        "## Limitations",
        "- Pre-layout: no wire capacitance and an ideal clock, so absolute delay and power "
        "will change after place-and-route.\n"
        "- Zero-delay simulation: glitches are not counted, so dynamic power is "
        "underestimated for all designs alike.\n"
        "- Uniform random inputs are not typical of image or CNN data.",

        "## Where the raw reports are",
        md(pd.DataFrame([
            {"file (results/synth/)": "`wrap_<design>.v`", "contents": "gate-level netlist"},
            {"file (results/synth/)": "`wrap_<design>_stat.txt`",
             "contents": "Yosys cell list, cell count and area"},
            {"file (results/synth/)": "`wrap_<design>_check.txt`",
             "contents": "Yosys structural check"},
            {"file (results/synth/)": "`wrap_<design>.timing.txt`",
             "contents": "OpenSTA critical (setup) path, step by step"},
            {"file (results/synth/)": "`wrap_<design>.hold.txt`",
             "contents": "OpenSTA shortest (hold) path, flip-flop to flip-flop"},
            {"file (results/synth/)": "`wrap_<design>.checks.txt`",
             "contents": "OpenSTA constraint check (empty = no problems)"},
            {"file (results/synth/)": "`wrap_<design>.power.txt`",
             "contents": "OpenSTA power report (N = 0 and a*b)"},
        ])),
    ]
    return "\n\n".join(sections) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default="results/flow_report.md")
    args = ap.parse_args()
    (REPO / args.out).write_text(report())
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
