#!/usr/bin/env bash
# scripts/tool_versions.sh -- record the exact tool versions used, so every
# number in results/ can be reproduced later (project rule 5).
#
# Usage: scripts/tool_versions.sh <yosys> <sta> <iverilog> <verilator> <python> <liberty file> [opensta source dir]
# Normally called through `make versions`, which passes the paths from flow/config.mk.
# Writes results/tool_versions.txt.

YOSYS=$1; STA=$2; IVERILOG=$3; VERILATOR=$4; PYTHON=$5; LIB=$6; STA_SRC=$7
OUT=results/tool_versions.txt
mkdir -p results

# Print "name: version", or "NOT FOUND" if the tool is missing.
ver() {
    local name=$1; shift
    local out
    if out=$("$@" 2>&1); then
        printf '%-12s %s\n' "$name:" "$(echo "$out" | head -n 1)"
    else
        printf '%-12s %s\n' "$name:" "NOT FOUND ($1)"
    fi
}

{
    echo "# Generated by scripts/tool_versions.sh -- do not edit by hand."
    echo "# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo
    echo "## System"
    printf '%-12s %s\n' "OS:" "$(. /etc/os-release && echo "$PRETTY_NAME")"
    printf '%-12s %s\n' "Kernel:" "$(uname -r)"
    echo
    echo "## EDA tools"
    ver yosys     "$YOSYS" -V
    ver opensta   "$STA" -version
    if [ -n "$STA_SRC" ] && [ -d "$STA_SRC/.git" ]; then
        printf '%-12s %s\n' "opensta src:" "$(git -C "$STA_SRC" log -1 --format='%H (%cd)' --date=short)"
    fi
    ver iverilog  "$IVERILOG" -V
    ver verilator "$VERILATOR" --version
    echo
    echo "## PDK"
    printf '%-12s %s\n' "liberty:" "$LIB"
    if [ -f "$LIB" ]; then
        printf '%-12s %s\n' "lib md5:" "$(md5sum "$LIB" | cut -d' ' -f1)"
        # The PDK folder has a SOURCES file naming the open_pdks commit.
        SRC="$(dirname "$LIB")/../../../SOURCES"
        [ -f "$SRC" ] && printf '%-12s %s\n' "pdk:" "$(tr '\n' ' ' < "$SRC")"
    else
        printf '%-12s %s\n' "lib md5:" "NOT FOUND"
    fi
    echo
    echo "## Python"
    ver python "$PYTHON" --version
    "$PYTHON" -m pip freeze 2>/dev/null \
        | grep -iE '^(numpy|pandas|matplotlib|scikit-image|scipy|pytest|torch|torchvision)=='
} > "$OUT"

echo "wrote $OUT"
cat "$OUT"
